AvaloniaCommunity/Prism.Avalonia

build/AvaloniaDependency.props, build/SampleApp.props
As the title says - upgrade Avalonia to the latest 0.10.7 version
=> Update Avalonia to 0.10.7

README.md, build/AvaloniaDependency.props, build/Base.props, build/BuildTargets.props, build/EmbedXaml.props, build/Nuget.props, build/SampleApp.props, samples/BootstrapperShellSample/BootstrapperShellSample.csproj, samples/DummyModule1/DummyModule1.csproj, samples/DummyModule2/DummyModule2.csproj, samples/ModulesSample.Infrastructure/ModulesSample.Infrastructure.csproj, samples/ModulesSample/ModulesSample.csproj, samples/SampleDialogApp/SampleDialogApp.csproj, samples/SampleMvvmApp/SampleMvvmApp.csproj, samples/ViewDiscovery/ViewDiscovery.csproj, src/Prism.Avalonia/Prism.Avalonia.csproj, src/Prism.DryIoc.Avalonia/Prism.DryIoc.Avalonia.csproj
* Updated NuGet packages
* Removed unnecessary dependencies
* Updated sample projects
=> Update to Support Avalonia v0.10.21

.gitignore, ChangeLog.md, ISSUE_TEMPLATE/feature-request.md, ISSUE_TEMPLATE/issue.md, build.ps1
Changelog notes and core repo components
=> Avalonia v10.21 cleanup

LICENSE, build/AvaloniaDependency.props, build/Base.props, build/SampleApp.props, samples/BootstrapperShellSample/Views/MainWindow.axaml
* Support for [Avalonia v11.0.0-rc1.1](https://www.nuget.org/packages/Avalonia/11.0.0-rc1.1)
* Updated version number schema. See Discussion https://github.com/AvaloniaCommunity/Prism.Avalonia/discussions/26#discussioncomment-6053353
=> Update to Support Avalonia v11.0.0-RC1.1

.editorconfig, build/Nuget.props, samples/DummyModule1/Views/DummyModuleView.axaml.cs, samples/SampleMvvmApp/ViewModels/SidebarViewModel.cs, src/Prism.Avalonia/Common/ObservableObject.cs, src/Prism.Avalonia/Interactivity/CommandBehaviorBase.cs, src/Prism.Avalonia/Modularity/DirectoryModuleCatalog.netcore.cs, tests/Avalonia/Prism.Avalonia.Tests/CompilerHelper.Desktop.cs, tests/Avalonia/Prism.Avalonia.Tests/Regions/RegionViewRegistryFixture.cs
* Reduced code warnings
* Updated VSSpell definitions
=> Avalonia v11.0.0-RC1.1 Cleanup

samples/SampleDialogApp/ViewModels/DialogViewModel.cs, samples/SampleDialogApp/ViewModels/MessageBoxViewModel.cs, samples/SampleDialogApp/Views/DialogView.axaml, samples/SampleDialogApp/Views/DialogView.axaml.cs, src/Prism.Avalonia/Services/Dialogs/DialogService.cs, src/Prism.Avalonia/Services/Dialogs/DialogWindow.axaml.cs, src/Prism.Avalonia/Services/Dialogs/IDialogService.cs
* The DialogService now allows for the parent window to be optionally specified
*   When not provided, the main window will be used by default
=> Dialog Host Window

src/Prism.Avalonia/Prism.Avalonia.csproj, tests/Avalonia/Prism.Avalonia.Tests/Modularity/ConfigurationStoreFixture.Desktop.cs, tests/Avalonia/Prism.Avalonia.Tests/Modularity/FileModuleTypeLoaderFixture.Desktop.cs, tests/Avalonia/Prism.Avalonia.Tests/Mvvm/ViewModelLocatorFixture.cs, tests/Avalonia/Prism.Avalonia.Tests/Regions/Behaviors/RegionManagerRegistrationBehaviorFixture.cs, tests/Avalonia/Prism.Avalonia.Tests/Regions/RegionManagerFixture.cs, tests/Avalonia/Prism.Avalonia.Tests/Regions/RegionViewRegistryFixture.cs, tests/Avalonia/Prism.Avalonia.Tests/Regions/SelectorRegionAdapterFixture.cs
=> Unit Test Fixes

src/Prism.Avalonia/Prism.Avalonia.csproj, tests/Avalonia/Prism.Avalonia.Tests/Modularity/ConfigurationStoreFixture.Desktop.cs, tests/Avalonia/Prism.Avalonia.Tests/Modularity/FileModuleTypeLoaderFixture.Desktop.cs, tests/Avalonia/Prism.Avalonia.Tests/Mvvm/ViewModelLocatorFixture.cs, tests/Avalonia/Prism.Avalonia.Tests/Regions/Behaviors/RegionManagerRegistrationBehaviorFixture.cs, tests/Avalonia/Prism.Avalonia.Tests/Regions/RegionManagerFixture.cs, tests/Avalonia/Prism.Avalonia.Tests/Regions/RegionViewRegistryFixture.cs, tests/Avalonia/Prism.Avalonia.Tests/Regions/SelectorRegionAdapterFixture.cs
Unit Test Fixes
* Merge pull request #77 from AvaloniaCommunity/feature/Avalonia-v11-Cleanup
=> Avalonia v0.10.x Unit Test Fixes

README.md, build/AvaloniaDependency.props, build/Base.props, build/Nuget.props, build/SampleApp.props, samples/BootstrapperShellSample/BootstrapperShellSample.csproj, samples/ModulesSample.Infrastructure/ModulesSample.Infrastructure.csproj, samples/ModulesSample/App.axaml.cs, samples/SampleDialogApp/Program.cs, samples/SampleDialogApp/SampleDialogApp.csproj, samples/SampleMvvmApp/Program.cs, samples/SampleMvvmApp/SampleMvvmApp.csproj, samples/ViewDiscovery/Program.cs, samples/ViewDiscovery/ViewDiscovery.csproj, src/Prism.Avalonia/Prism.Avalonia.csproj, src/Prism.DryIoc.Avalonia/Prism.DryIoc.Avalonia.csproj, tests/Avalonia/Prism.Avalonia.Tests/Prism.Avalonia.Tests.csproj
Updated code base to support Avalonia v11.0.0 release 🍾 🎆 🥳
=> Upgraded code base to support Avalonia v11.0.0 GA release

README.md
Announcement for Prism.Avalonia v9.0-beta
=> Announcement

samples/SampleMvvmApp/App.axaml.cs, samples/SampleMvvmApp/RegionAdapters/ItemsControlRegionAdapter.cs, samples/SampleMvvmApp/RegionNames.cs, samples/SampleMvvmApp/SampleMvvmApp.csproj, samples/SampleMvvmApp/Views/Setting1View.axaml, samples/SampleMvvmApp/Views/Setting1View.axaml.cs, samples/SampleMvvmApp/Views/Setting2View.axaml, samples/SampleMvvmApp/Views/Setting2View.axaml.cs, samples/SampleMvvmApp/Views/SettingsView.axaml, samples/SampleMvvmApp/readme.md
... with multiple views, using a dynamic collection of settings views to illustrate usage
=> Sample using a custom ItemsControlRegionAdapter to populate an ItemsControl

ChangeLog.md, LICENSE, Prism.Avalonia.sln, build/Base.props, build/BuildTargets.props, samples/BootstrapperShellSample/BootstrapperShellSample.csproj, samples/DummyModule1/DummyModule1.csproj, samples/DummyModule2/DummyModule2.csproj, samples/ModulesSample.Infrastructure/ModulesSample.Infrastructure.csproj, samples/ModulesSample/ModulesSampleApp.csproj, samples/SampleDialogApp/SampleDialogApp.csproj, samples/SampleMvvmApp/SampleMvvmApp.csproj, samples/ViewDiscovery/ViewDiscovery.csproj, src/Prism.Avalonia/Prism.Avalonia.csproj, src/Prism.DryIoc.Avalonia/Prism.DryIoc.Avalonia.csproj, tests/Avalonia/Prism.Avalonia.Tests/Prism.Avalonia.Tests.csproj
=> Target Framework .NET 8

build/AvaloniaDependency.props, build/Base.props, build/Nuget.props, build/SampleApp.props, samples/BootstrapperShellSample/App.axaml.cs, samples/SampleMvvmApp/Views/SettingsView.axaml, src/Prism.Avalonia/Prism.Avalonia.csproj
Feature Includes:
* Upgraded Avalonia NuGet packages to 11.0.7
* Removed unused CommonServiceLocator
=> Upgraded Avalonia NuGet packages to 11.0.7

README.md
Moved the "Contributing" rules to top of the Readme document
=> README.md Moved Contributing Rules to the top

build/Base.props, build/PrismDependency.props
Changed NuGet package to Prism.Core v9.0.264-pre
=> Retarget Prism v9.0.264-pre

Upgrading-Prism.md, src/Prism.Avalonia/Extensions/CollectionExtensions.cs
=> Prism v9.0.271-pre Documentation

Directory.Packages.props, src/Prism.DryIoc.Avalonia/build/Package.targets
Upgrade NuGet packages for v9.0.401-pre compatibility
* Updated: Prism.Container.*, DryIoc, XUnit.*
* Added PolySharp
=> v9.0.401 - Upgrade Packages

Directory.Packages.props, src/Prism.Avalonia/Common/MvvmHelpers.cs, src/Prism.Avalonia/Ioc/IContainerRegistryExtensions.cs, src/Prism.Avalonia/Navigation/Regions/RegionAdapterMappings.cs, src/Prism.Avalonia/Prism.Avalonia.csproj
Upgrade the core framework
* DynamicallyAccessedMembers Attribute for linker hints
=> v9.0.401-pre Upgrade Core Framework

ChangeLog.md, PrismLibrary_Avalonia.slnf, README.md, build/Base.props, e2e/SampleMvvmApp/RegionAdapters/ItemsControlRegionAdapter.cs
* Bumped the version to `v9.0.401.11000-pre`
* Documentation
* Code cleanup
=> Prism v9.0.401-pre - Version Number and Documentation

ChangeLog.md, Directory.Packages.props, PrismLibrary_Avalonia.slnf, README.md, build/Base.props, e2e/SampleMvvmApp/RegionAdapters/ItemsControlRegionAdapter.cs, src/Prism.Avalonia/Common/MvvmHelpers.cs, src/Prism.Avalonia/Ioc/IContainerRegistryExtensions.cs, src/Prism.Avalonia/Navigation/Regions/RegionAdapterMappings.cs, src/Prism.Avalonia/Prism.Avalonia.csproj, src/Prism.DryIoc.Avalonia/build/Package.targets
Make Prism.Avalonia compatible with Prism.Core v9.0.401-pre
* Fixed typos
* DynamicallyAccessedMembers Attribute for linker hints
* Upgraded NuGet DryIoc to 5.4.3
=> v9.0.401-pre

Code-of-Conduct.md
Basic code of conduct.
_Keep it old-school_
=> Code of Conduct

Contributing.md
Added contributing  from README.md, to make GitHub's "community standards" happy
Really, GitHub?! You're making me duplicate this?
=> Contributing

Directory.Packages.props, tests/Avalonia/Prism.IocContainer.Avalonia.Tests.Support/Prism.IocContainer.Avalonia.Tests.Support.csproj
As part of maintenance, update the following packages:
* Prism.Containers.DryIoc
* XUnit
* Coverlet
* Microsoft.NET.Test.Sdk
=> [Maint] Update NuGet Packages

Directory.Packages.props
Update NuGet Packages for Tests
=> [Maint] Update NuGet Packages for Tests

README.md
Added link to Prism.Avalonia project templates
https://github.com/SuessLabs/Prism.Avalonia.Templates
=> Prism.Avalonia Templates link

README.md
=>  Notice for GA coming soon

README.md
Prism.Avalonia is moving to the official Prism repository where future releases and support will be continued.
Development efforts will move forward over there and I am fully committed to keeping this project alive 👍
=> Moving To Prism Library
